[package]
name = "mozwire"
description = "MozillaVPN wireguard configuration manager"
categories = ["command-line-utilities", "authentication", "config"]
keywords = ["wireguard", "vpn", "mozilla", "cross-platform", "linux"]
authors = ["Nils <nils@nilsand.re>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/NilsIrl/MozWire/"
readme = "README.md"
version = "0.8.1"
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.60", features = ["color", "derive", "env", "wrap_help"] }
percent-encoding = "2.3.2"
rand = "0.8.5"
regex = "1.12.3"
reqwest = { version = "0.13.2", default-features = false, features = ["default-tls", "blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
sys-info = "0.9.1"
tiny_http = "0.12.0"
webbrowser = "1.1.0"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
